# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xelyon < Formula
  desc "高速・軽量なLLMコーディングアシスタント"
  homepage "https://github.com/susugadx/xelyon-cli"
  version "0.46.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/susugadx/xelyon-cli/releases/download/v0.46.0/xelyon-cli_0.46.0_darwin_amd64.tar.gz"
      sha256 "5d8a0203f9ed8639d60ced9bfae4722578fc59bef847a3e37c3cd02697d9cc06"

      def install
        bin.install "xelyon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/susugadx/xelyon-cli/releases/download/v0.46.0/xelyon-cli_0.46.0_darwin_arm64.tar.gz"
      sha256 "7e2f5f898a513c846c594bfc7d6ff0873f185566de9fd2d2f8a75ddeb9863f1b"

      def install
        bin.install "xelyon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/susugadx/xelyon-cli/releases/download/v0.46.0/xelyon-cli_0.46.0_linux_amd64.tar.gz"
      sha256 "8f2c08bc2ca0fffb3bab4e73d9405a34aed76c31dd8da60809cf177e9b05eead"
      def install
        bin.install "xelyon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/susugadx/xelyon-cli/releases/download/v0.46.0/xelyon-cli_0.46.0_linux_arm64.tar.gz"
      sha256 "5e18561a67013ee418cca2a9f0f6b2a0b736c8f482139479dd22644d4aa5dcf4"
      def install
        bin.install "xelyon"
      end
    end
  end

  test do
    system "#{bin}/xelyon", "--version"
  end
end
